### PR TITLE
✨ feature(logging): Add proper structlog support

### PR DESCRIPTION
**Pull request by kiloreven**
Improved structlog support in Troncos, which enables developers to employ the full stack of structlog for logging and formatting. It's implemented parallel to the existing formatters to allow for adoption without affecting other applications that only employ the standard Python logging framework.

I think we should consider moving to structlog-only at some point, and phase out the old formatters, but that's a job (and a discussion for later).

This commit also adds some optional parameters for `init_logging_basic` (`app_release`, `environment`, `app_name`) which are annotated on all log entries after the logger has been configured.

For the examples below I've used the following config,
``` python
    init_logging_structlog(
        level=settings.LOG_LEVEL,
        formatter=settings.LOG_FORMAT,
        app_release="0.0.0",
        environment="prod",
        app_name="identifica",
    )
```

The final implementations should use variable values where available instead,

``` python
    init_logging_structlog(
        level=settings.LOG_LEVEL,
        formatter=settings.LOG_FORMAT,
        app_release=settings.RELEASE,
        environment=settings.ENVIRONMENT,
        app_name=settings.SERVICE,
    )
```

**logfmt**
2022-10-31T12:24:41+01:00

**cli**
2022-10-31T12:25:02+01:00

### CODE REVIEW

**Review by eirsyl — COMMENTED** [review]
I guess this will "work", but it also makes it harder for devs to apply custom config. It will probably work in most cases, but I don't think more complex apps like trex will move to this straight away.  

It also looks like you are missing the context_vars feature, https://www.structlog.org/en/stable/contextvars.html. We use that to add metadata like user_ids to all logs within a request.

**Comment by eirsyl** [comment]
I don't see `trace_injection_processor` from https://github.com/kolonialno/troncos/pull/11 being used either. Did you forget to add the span context to the logs?

**Comment by kiloreven** [comment]
@gbbirkisson: I'll look into isolating the structlog config a little from the regular logging config, so that we can remove structlog as a hard dependency.

@eirsyl: Good catch about the context vars merge processor; I'll add that. The `trace_injection_processor` also went under my radar, fixing that as well as moving the structlog-specific initiation to `troncos/framworks/structlog`.

**Comment by kiloreven** [comment]
@gbbirkisson, @eirsyl: Made some changes after your feedback https://github.com/kolonialno/troncos/pull/38/commits/a265c31b3db7c9ff3861a7a4e90a16bd8f3107c5

**Comment by kiloreven** [comment]
Quick mention to link, https://github.com/kolonialno/troncos/pull/38

**Comment by kiloreven** [comment]
Mentioning Linear issue, ORGEN-141

**Pull request merged**
