### PR TITLE
trace_class add tracing for classmethod and staticmethdod

### PR DESCRIPTION
**Pull request by EeroPaukkonen**
trace_class will trace `classmethods`, `staticmethod` by default. 
This does not include `property`. I do not have strong opinion about property to either direction.
 
Slightly cleaned test folder structure.
Also not sure if enabling this by default would be issue for some 🤷

### CODE REVIEW

**Comment by gbbirkisson** [comment]
I think `classmethods` and `staticmethods` should probably be traced by default. It is easy to opt out if you don't want that. I'm not sure about `property` though. Its probably overkill to trace that by default. You can always explicitly trace them if you want. Let me do some digging.

**Comment by gbbirkisson** [comment]
I think `classmethods` and `staticmethods` should probably be traced by default. It is easy to opt out if you don't want that. I'm not sure about `property` though. Its probably overkill to trace that by default. You can always explicitly trace them if you want. Let me do some digging.

**Comment by EeroPaukkonen** [comment]
> I think classmethods and staticmethods should probably be traced by default. It is easy to opt out if you don't want that. I'm not sure about property though. Its probably overkill to trace that by default. You can always explicitly trace them if you want. Let me do some digging.

Yea I also had reservations about `property` makes sense to keep it out.

**Review by gbbirkisson — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
